# For more information: https://laravel.com/docs/sail
version: '3'
services:
  laravel.test:
    image: electricbluefishproductions/anemone-api
    ports:
      - '${APP_PORT:-80}:8000'
    networks:
      - sail
    depends_on:
      - mysql
    volumes:
      - '${FILES}:/app/public/images'
      - '/home/ian/anemone.env:/app/.env'
  scraper:
    image: electricbluefishproductions/anemone-scrapper
    ports:
      - '${SCRAPER_PORT}:5000'
    networks:
      - sail
  app:
    image: avariantphi/anemone-app
    ports:
      - '${ANEMONE_WEB_APP_PORT}:80'
    networks:
      - sail
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '${PMA_PORT}:80'
    environment:
      - PMA_HOST=mysql
      - PMA_ABSOLUTE_URI=https://anemone.avalonbloom.com/pma
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
  sail-meilisearch:
    driver: local
